/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ReplyQueueRouteImport } from './routes/reply-queue'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DevRouteImport } from './routes/dev'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSectionRouteImport } from './routes/settings.$section'
import { Route as RulesIdRouteImport } from './routes/rules.$id'
import { Route as MMailboxRouteImport } from './routes/m.$mailbox'
import { Route as ComposeNewRouteImport } from './routes/compose.new'
import { Route as ComposeDraftIdRouteImport } from './routes/compose.$draftId'
import { Route as AnalyticsDashboardRouteImport } from './routes/analytics.$dashboard'
import { Route as AccountsKeyRouteImport } from './routes/accounts.$key'
import { Route as MSavedSlugRouteImport } from './routes/m.saved.$slug'
import { Route as MLabelNameRouteImport } from './routes/m.label.$name'
import { Route as MMailboxThreadIdRouteImport } from './routes/m.$mailbox.$threadId'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplyQueueRoute = ReplyQueueRouteImport.update({
  id: '/reply-queue',
  path: '/reply-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/settings/$section',
  path: '/settings/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIdRoute = RulesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RulesRoute,
} as any)
const MMailboxRoute = MMailboxRouteImport.update({
  id: '/m/$mailbox',
  path: '/m/$mailbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeNewRoute = ComposeNewRouteImport.update({
  id: '/compose/new',
  path: '/compose/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeDraftIdRoute = ComposeDraftIdRouteImport.update({
  id: '/compose/$draftId',
  path: '/compose/$draftId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsDashboardRoute = AnalyticsDashboardRouteImport.update({
  id: '/$dashboard',
  path: '/$dashboard',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AccountsKeyRoute = AccountsKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => AccountsRoute,
} as any)
const MSavedSlugRoute = MSavedSlugRouteImport.update({
  id: '/m/saved/$slug',
  path: '/m/saved/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MLabelNameRoute = MLabelNameRouteImport.update({
  id: '/m/label/$name',
  path: '/m/label/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const MMailboxThreadIdRoute = MMailboxThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => MMailboxRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/analytics': typeof AnalyticsRouteWithChildren
  '/dev': typeof DevRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/onboarding': typeof OnboardingRoute
  '/reply-queue': typeof ReplyQueueRoute
  '/rules': typeof RulesRouteWithChildren
  '/screener': typeof ScreenerRoute
  '/search': typeof SearchRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/accounts/$key': typeof AccountsKeyRoute
  '/analytics/$dashboard': typeof AnalyticsDashboardRoute
  '/compose/$draftId': typeof ComposeDraftIdRoute
  '/compose/new': typeof ComposeNewRoute
  '/m/$mailbox': typeof MMailboxRouteWithChildren
  '/rules/$id': typeof RulesIdRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/m/$mailbox/$threadId': typeof MMailboxThreadIdRoute
  '/m/label/$name': typeof MLabelNameRoute
  '/m/saved/$slug': typeof MSavedSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/analytics': typeof AnalyticsRouteWithChildren
  '/dev': typeof DevRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/onboarding': typeof OnboardingRoute
  '/reply-queue': typeof ReplyQueueRoute
  '/rules': typeof RulesRouteWithChildren
  '/screener': typeof ScreenerRoute
  '/search': typeof SearchRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/accounts/$key': typeof AccountsKeyRoute
  '/analytics/$dashboard': typeof AnalyticsDashboardRoute
  '/compose/$draftId': typeof ComposeDraftIdRoute
  '/compose/new': typeof ComposeNewRoute
  '/m/$mailbox': typeof MMailboxRouteWithChildren
  '/rules/$id': typeof RulesIdRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/m/$mailbox/$threadId': typeof MMailboxThreadIdRoute
  '/m/label/$name': typeof MLabelNameRoute
  '/m/saved/$slug': typeof MSavedSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/analytics': typeof AnalyticsRouteWithChildren
  '/dev': typeof DevRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/onboarding': typeof OnboardingRoute
  '/reply-queue': typeof ReplyQueueRoute
  '/rules': typeof RulesRouteWithChildren
  '/screener': typeof ScreenerRoute
  '/search': typeof SearchRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/accounts/$key': typeof AccountsKeyRoute
  '/analytics/$dashboard': typeof AnalyticsDashboardRoute
  '/compose/$draftId': typeof ComposeDraftIdRoute
  '/compose/new': typeof ComposeNewRoute
  '/m/$mailbox': typeof MMailboxRouteWithChildren
  '/rules/$id': typeof RulesIdRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/m/$mailbox/$threadId': typeof MMailboxThreadIdRoute
  '/m/label/$name': typeof MLabelNameRoute
  '/m/saved/$slug': typeof MSavedSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/analytics'
    | '/dev'
    | '/diagnostics'
    | '/onboarding'
    | '/reply-queue'
    | '/rules'
    | '/screener'
    | '/search'
    | '/subscriptions'
    | '/accounts/$key'
    | '/analytics/$dashboard'
    | '/compose/$draftId'
    | '/compose/new'
    | '/m/$mailbox'
    | '/rules/$id'
    | '/settings/$section'
    | '/m/$mailbox/$threadId'
    | '/m/label/$name'
    | '/m/saved/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/analytics'
    | '/dev'
    | '/diagnostics'
    | '/onboarding'
    | '/reply-queue'
    | '/rules'
    | '/screener'
    | '/search'
    | '/subscriptions'
    | '/accounts/$key'
    | '/analytics/$dashboard'
    | '/compose/$draftId'
    | '/compose/new'
    | '/m/$mailbox'
    | '/rules/$id'
    | '/settings/$section'
    | '/m/$mailbox/$threadId'
    | '/m/label/$name'
    | '/m/saved/$slug'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/analytics'
    | '/dev'
    | '/diagnostics'
    | '/onboarding'
    | '/reply-queue'
    | '/rules'
    | '/screener'
    | '/search'
    | '/subscriptions'
    | '/accounts/$key'
    | '/analytics/$dashboard'
    | '/compose/$draftId'
    | '/compose/new'
    | '/m/$mailbox'
    | '/rules/$id'
    | '/settings/$section'
    | '/m/$mailbox/$threadId'
    | '/m/label/$name'
    | '/m/saved/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  DevRoute: typeof DevRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  OnboardingRoute: typeof OnboardingRoute
  ReplyQueueRoute: typeof ReplyQueueRoute
  RulesRoute: typeof RulesRouteWithChildren
  ScreenerRoute: typeof ScreenerRoute
  SearchRoute: typeof SearchRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  ComposeDraftIdRoute: typeof ComposeDraftIdRoute
  ComposeNewRoute: typeof ComposeNewRoute
  MMailboxRoute: typeof MMailboxRouteWithChildren
  SettingsSectionRoute: typeof SettingsSectionRoute
  MLabelNameRoute: typeof MLabelNameRoute
  MSavedSlugRoute: typeof MSavedSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reply-queue': {
      id: '/reply-queue'
      path: '/reply-queue'
      fullPath: '/reply-queue'
      preLoaderRoute: typeof ReplyQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$id': {
      id: '/rules/$id'
      path: '/$id'
      fullPath: '/rules/$id'
      preLoaderRoute: typeof RulesIdRouteImport
      parentRoute: typeof RulesRoute
    }
    '/m/$mailbox': {
      id: '/m/$mailbox'
      path: '/m/$mailbox'
      fullPath: '/m/$mailbox'
      preLoaderRoute: typeof MMailboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose/new': {
      id: '/compose/new'
      path: '/compose/new'
      fullPath: '/compose/new'
      preLoaderRoute: typeof ComposeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose/$draftId': {
      id: '/compose/$draftId'
      path: '/compose/$draftId'
      fullPath: '/compose/$draftId'
      preLoaderRoute: typeof ComposeDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/$dashboard': {
      id: '/analytics/$dashboard'
      path: '/$dashboard'
      fullPath: '/analytics/$dashboard'
      preLoaderRoute: typeof AnalyticsDashboardRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/accounts/$key': {
      id: '/accounts/$key'
      path: '/$key'
      fullPath: '/accounts/$key'
      preLoaderRoute: typeof AccountsKeyRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/m/saved/$slug': {
      id: '/m/saved/$slug'
      path: '/m/saved/$slug'
      fullPath: '/m/saved/$slug'
      preLoaderRoute: typeof MSavedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/label/$name': {
      id: '/m/label/$name'
      path: '/m/label/$name'
      fullPath: '/m/label/$name'
      preLoaderRoute: typeof MLabelNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$mailbox/$threadId': {
      id: '/m/$mailbox/$threadId'
      path: '/$threadId'
      fullPath: '/m/$mailbox/$threadId'
      preLoaderRoute: typeof MMailboxThreadIdRouteImport
      parentRoute: typeof MMailboxRoute
    }
  }
}

interface AccountsRouteChildren {
  AccountsKeyRoute: typeof AccountsKeyRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsKeyRoute: AccountsKeyRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface AnalyticsRouteChildren {
  AnalyticsDashboardRoute: typeof AnalyticsDashboardRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsDashboardRoute: AnalyticsDashboardRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface RulesRouteChildren {
  RulesIdRoute: typeof RulesIdRoute
}

const RulesRouteChildren: RulesRouteChildren = {
  RulesIdRoute: RulesIdRoute,
}

const RulesRouteWithChildren = RulesRoute._addFileChildren(RulesRouteChildren)

interface MMailboxRouteChildren {
  MMailboxThreadIdRoute: typeof MMailboxThreadIdRoute
}

const MMailboxRouteChildren: MMailboxRouteChildren = {
  MMailboxThreadIdRoute: MMailboxThreadIdRoute,
}

const MMailboxRouteWithChildren = MMailboxRoute._addFileChildren(
  MMailboxRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  DevRoute: DevRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  OnboardingRoute: OnboardingRoute,
  ReplyQueueRoute: ReplyQueueRoute,
  RulesRoute: RulesRouteWithChildren,
  ScreenerRoute: ScreenerRoute,
  SearchRoute: SearchRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  ComposeDraftIdRoute: ComposeDraftIdRoute,
  ComposeNewRoute: ComposeNewRoute,
  MMailboxRoute: MMailboxRouteWithChildren,
  SettingsSectionRoute: SettingsSectionRoute,
  MLabelNameRoute: MLabelNameRoute,
  MSavedSlugRoute: MSavedSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
