//! Example mxr adapter skeleton.
//!
//! Copy this crate into a standalone repository, replace the stubbed provider
//! methods with your real implementation, then run the conformance helpers from
//! `mxr-provider-fake`.

use async_trait::async_trait;
use mxr_core::{
    AccountId, Address, Draft, Label, MailSendProvider, MailSyncProvider, MutateCaps, Mutation,
    MxrError, PushCaps, SearchCaps, SendReceipt, SyncBatch, SyncCapabilities, SyncCaps, SyncCursor,
};

pub struct ExampleSyncProvider {
    account_id: AccountId,
}

impl ExampleSyncProvider {
    pub fn new(account_id: AccountId) -> Self {
        Self { account_id }
    }
}

#[async_trait]
impl MailSyncProvider for ExampleSyncProvider {
    fn name(&self) -> &str {
        "example"
    }

    fn account_id(&self) -> &AccountId {
        &self.account_id
    }

    /// Start with everything off and flip a flag on only once the
    /// corresponding behavior is really implemented — the daemon trusts
    /// this and will route work to you based on it.
    fn capabilities(&self) -> SyncCapabilities {
        SyncCapabilities {
            sync: SyncCaps {
                delta: false,
                native_threading: false,
            },
            mutate: MutateCaps {
                labels: false,
                batch_operations: false,
                custom_keywords: false,
            },
            search: SearchCaps { server_side: false },
            push: PushCaps { streaming: false },
        }
    }

    async fn authenticate(&mut self) -> Result<(), MxrError> {
        Err(MxrError::Provider(
            "authenticate not implemented".to_string(),
        ))
    }

    async fn refresh_auth(&mut self) -> Result<(), MxrError> {
        Err(MxrError::Provider(
            "refresh_auth not implemented".to_string(),
        ))
    }

    async fn sync_labels(&self) -> Result<Vec<Label>, MxrError> {
        Err(MxrError::Provider(
            "sync_labels not implemented".to_string(),
        ))
    }

    async fn sync_messages(&self, _cursor: &SyncCursor) -> Result<SyncBatch, MxrError> {
        Err(MxrError::Provider(
            "sync_messages not implemented".to_string(),
        ))
    }

    async fn fetch_attachment(
        &self,
        _provider_message_id: &str,
        _provider_attachment_id: &str,
    ) -> Result<Vec<u8>, MxrError> {
        Err(MxrError::Provider(
            "fetch_attachment not implemented".to_string(),
        ))
    }

    /// Every message mutation arrives here as a single entry point.
    ///
    /// `mutation_id` is a stable UUIDv7 supplied by the caller: the daemon's
    /// `mutation_dedup_log` (24h window) already skips duplicate applies on
    /// retry, so an adapter may ignore it — or use it for its own idempotency.
    ///
    /// `Mutation::ModifyLabels` means stable multi-assign label semantics only
    /// when `capabilities().mutate.labels` is true; folder-based providers map
    /// it to move/copy instead. Reject `SetKeywords` unless
    /// `capabilities().mutate.custom_keywords` is true rather than silently
    /// dropping it.
    async fn apply_mutation(
        &self,
        _mutation_id: &str,
        mutation: &Mutation,
    ) -> Result<(), MxrError> {
        let op = match mutation {
            Mutation::ModifyLabels { .. } => "modify_labels",
            Mutation::Trash { .. } => "trash",
            Mutation::SetRead { .. } => "set_read",
            Mutation::SetStarred { .. } => "set_starred",
            Mutation::SetKeywords { .. } => "set_keywords",
        };
        Err(MxrError::Provider(format!("{op} not implemented")))
    }
}

pub struct ExampleSendProvider;

#[async_trait]
impl MailSendProvider for ExampleSendProvider {
    fn name(&self) -> &str {
        "example"
    }

    /// `rfc2822_message_id` is generated by the daemon and must be used as the
    /// outgoing `Message-ID` header, so the sent copy reconciles with what the
    /// provider later syncs back.
    async fn send(
        &self,
        _draft: &Draft,
        _from: &Address,
        _rfc2822_message_id: &str,
    ) -> Result<SendReceipt, MxrError> {
        Err(MxrError::Provider("send not implemented".to_string()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn skeleton_constructs_provider() {
        let provider = ExampleSyncProvider::new(AccountId::new());
        assert_eq!(provider.name(), "example");
    }
}
