//! Optimistic-mutation snapshots and rollback infrastructure.
//!
//! Every queued mutation is assigned a [`MutationId`] and captures a
//! [`MutationSnapshot`] of the pre-mutation state at queue time. When the
//! daemon reports a reconciliation failure for a given ID, the App replays
//! the snapshot to revert the optimistic local-state change.
//!
//! Snapshots are bounded: only the most recent 64 are retained. Older
//! snapshots are dropped silently — by then the daemon has had ample time
//! to ack or fail, so a missing snapshot for a very old mutation just
//! degrades to "we can't roll back this one specifically; surface the
//! error and let the next sync reconcile."

use std::collections::HashMap;
use std::collections::VecDeque;

use mxr_core::id::MessageId;
use mxr_core::types::MessageFlags;
use mxr_protocol::Request;

use super::MutationEffect;

/// Maximum number of in-flight mutation snapshots retained for rollback.
/// Sized for "more than any reasonable burst of user actions"; older
/// snapshots are evicted FIFO.
pub const MUTATION_SNAPSHOT_CAPACITY: usize = 64;

/// Process-local identifier for an optimistic mutation. Generated by the
/// App at queue time and threaded through the IPC layer so the daemon can
/// reference the same mutation when reporting reconciliation outcomes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct MutationId(u64);

impl MutationId {
    pub fn raw(self) -> u64 {
        self.0
    }
}

/// Monotonic counter for assigning fresh [`MutationId`]s.
#[derive(Debug, Default)]
pub struct MutationIdGenerator {
    next: u64,
}

impl MutationIdGenerator {
    pub fn next_id(&mut self) -> MutationId {
        let id = MutationId(self.next);
        self.next = self.next.wrapping_add(1);
        id
    }
}

/// A mutation queued for the daemon, carrying enough context to apply it
/// (request + completion effect) and to roll back its optimistic effect on
/// failure (snapshot ID, looked up in [`App::mutation_snapshots`]).
#[derive(Debug, Clone)]
pub struct QueuedMutation {
    pub id: MutationId,
    pub request: Request,
    pub effect: MutationEffect,
}

/// Pre-mutation state captured for a single optimistic effect. On failure,
/// the inverse application restores the relevant fields without a network
/// round-trip.
#[derive(Debug, Clone)]
pub enum MutationSnapshot {
    /// Prior flags for messages whose flags were optimistically updated.
    Flags(Vec<(MessageId, MessageFlags)>),
    /// Prior label-provider-id sets for messages whose labels were
    /// optimistically modified.
    Labels(Vec<(MessageId, Vec<String>)>),
    /// Effect doesn't carry rollback state (e.g. `RefreshList`,
    /// `StatusOnly`, `SentSuccess`). Failure routing surfaces the error
    /// but no inverse application runs.
    None,
}

/// Bounded snapshot store keyed by [`MutationId`]. Tracks insertion order
/// in a FIFO queue so eviction is O(1) once capacity is reached.
#[derive(Debug, Default)]
pub struct MutationSnapshotStore {
    by_id: HashMap<MutationId, MutationSnapshot>,
    insertion_order: VecDeque<MutationId>,
}

impl MutationSnapshotStore {
    pub fn insert(&mut self, id: MutationId, snapshot: MutationSnapshot) {
        if self.by_id.len() >= MUTATION_SNAPSHOT_CAPACITY {
            if let Some(oldest) = self.insertion_order.pop_front() {
                self.by_id.remove(&oldest);
            }
        }
        self.by_id.insert(id, snapshot);
        self.insertion_order.push_back(id);
    }

    pub fn take(&mut self, id: MutationId) -> Option<MutationSnapshot> {
        let snapshot = self.by_id.remove(&id)?;
        if let Some(pos) = self.insertion_order.iter().position(|other| *other == id) {
            self.insertion_order.remove(pos);
        }
        Some(snapshot)
    }

    pub fn len(&self) -> usize {
        self.by_id.len()
    }

    pub fn is_empty(&self) -> bool {
        self.by_id.is_empty()
    }
}
