/*
 * "Draft for me" and refine: LLM draft generation for the compose session,
 * plus the tone/length dials that steer it.
 */

import { useMutation } from "@tanstack/react-query";
import { useState, type Dispatch, type MutableRefObject, type SetStateAction } from "react";
import { toast } from "sonner";

import { apiFetch } from "@/api/client";
import type {
  DraftLengthHint,
  DraftRefineKnobs,
  DraftSuggestionResponse,
  VoiceRegister,
} from "../types";
import {
  errorMessage,
  firstAddress,
  type ComposeDraftState,
  type ComposeIntent,
} from "./composeDraft";

interface DraftAssistInput {
  intent: ComposeIntent;
  draftRef: MutableRefObject<ComposeDraftState | null>;
  setDraft: Dispatch<SetStateAction<ComposeDraftState | null>>;
  setDirty: Dispatch<SetStateAction<boolean>>;
}

export function useDraftAssist({ intent, draftRef, setDraft, setDirty }: DraftAssistInput) {
  const [aiPurpose, setAiPurpose] = useState("");
  const [aiRegister, setAiRegister] = useState<VoiceRegister>("neutral");
  const [aiLength, setAiLength] = useState<DraftLengthHint>("medium");
  // Tone/length are inferred from the relationship by default; only send the
  // dials as an override once the user has adjusted them.
  const [aiOverridden, setAiOverridden] = useState(false);
  const [refineContext, setRefineContext] = useState("");
  const [draftSuggestion, setDraftSuggestion] = useState<DraftSuggestionResponse | null>(null);
  const [assistOpen, setAssistOpen] = useState(false);

  const draftForMe = useMutation({
    mutationFn: async () => {
      const current = draftRef.current;
      if (!current) throw new Error("No draft is open");
      const email = firstAddress(current.frontmatter.to);
      if (!email) throw new Error("Add a recipient before drafting");
      const purpose = aiPurpose.trim() || current.frontmatter.subject.trim();
      if (!purpose) throw new Error("Describe what this email should do");
      return apiFetch<DraftSuggestionResponse>("/api/v1/mail/drafts/compose", {
        method: "POST",
        body: {
          account_id: current.accountId,
          to: { name: null, email },
          instruction: purpose,
          // Reply/forward: hand the daemon the source message so it drafts
          // against the whole conversation.
          ...(intent.messageId ? { source_message_id: intent.messageId } : {}),
          // Only override the inferred tone/length once the user adjusts it.
          ...(aiOverridden ? { register: aiRegister, length_hint: aiLength } : {}),
        },
      });
    },
    onSuccess: (suggestion) => applyDraftSuggestion(suggestion, "Draft inserted"),
    onError: (error) =>
      toast.error("Draft generation failed", { description: errorMessage(error) }),
  });
  const refineDraft = useMutation({
    mutationFn: async (knobs: DraftRefineKnobs) => {
      if (!intent.draftId) throw new Error("Refine is available for saved mxr drafts");
      return apiFetch<DraftSuggestionResponse>("/api/v1/mail/drafts/refine", {
        method: "POST",
        body: {
          draft_id: intent.draftId,
          knobs,
        },
      });
    },
    onSuccess: (suggestion) => applyDraftSuggestion(suggestion, "Draft refined"),
    onError: (error) => toast.error("Refine failed", { description: errorMessage(error) }),
  });

  function applyDraftSuggestion(suggestion: DraftSuggestionResponse, title: string) {
    setDraft((current) => (current ? { ...current, bodyMarkdown: suggestion.body } : current));
    setDraftSuggestion(suggestion);
    // Reflect the inferred tone in the dials (unless the user overrode it),
    // so opening "Adjust" shows what was actually used.
    if (!aiOverridden) {
      if (suggestion.inferred_register) setAiRegister(suggestion.inferred_register);
      if (suggestion.inferred_length) setAiLength(suggestion.inferred_length);
    }
    setDirty(true);
    toast.success(title, { description: `Generated by ${suggestion.model}` });
  }

  function runRefine(knobs: DraftRefineKnobs) {
    const addContext = refineContext.trim();
    refineDraft.mutate({
      ...knobs,
      ...(addContext ? { add_context: addContext } : {}),
    });
  }

  return {
    assistOpen,
    setAssistOpen,
    aiPurpose,
    setAiPurpose,
    aiRegister,
    onRegisterChange: (value: VoiceRegister) => {
      setAiRegister(value);
      setAiOverridden(true);
    },
    aiLength,
    onLengthChange: (value: DraftLengthHint) => {
      setAiLength(value);
      setAiOverridden(true);
    },
    aiOverridden,
    resetTone: () => setAiOverridden(false),
    refineContext,
    setRefineContext,
    draftSuggestion,
    generateDraft: () => draftForMe.mutate(),
    generating: draftForMe.isPending,
    runRefine,
    refining: refineDraft.isPending,
    canRefine: Boolean(intent.draftId),
  };
}
